# Generated by Django 4.1.7 on 2023-11-19 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=50)),
                ('conference_description', models.CharField(blank=True, max_length=225)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paper_description', models.TextField()),
                ('paper_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper_upload', models.FileField(upload_to='papers/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('author_name', models.CharField(max_length=70)),
                ('Auth_email', models.EmailField(default='example@example.com', max_length=254)),
                ('Auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('Auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('corresponding_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('corresponding_auth_email', models.EmailField(default='corresponding@example.com', max_length=254)),
                ('corresponding_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('corresponding_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('other_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('other_auth_email', models.CharField(default='other@example.com', max_length=150)),
                ('other_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('other_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('paper_keyword', models.CharField(default='No keywords', max_length=100)),
                ('reviewer_comments', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(default='None', max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(default='None', max_length=15)),
                ('password', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_auth', models.BooleanField(default=False)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_conference_admin', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=70, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'is_reviewer': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('highest_qualifications', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('designations', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='reviewer/profile_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='reviewer/resumes/')),
                ('is_ok', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resubmite_Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paper_description', models.TextField()),
                ('paper_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper_upload', models.FileField(upload_to='Resubmited_papers/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('author_name', models.CharField(max_length=70)),
                ('Auth_email', models.EmailField(default='example@example.com', max_length=254)),
                ('Auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('Auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('corresponding_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('corresponding_auth_email', models.EmailField(default='corresponding@example.com', max_length=254)),
                ('corresponding_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('corresponding_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('other_auth_name', models.CharField(default='Unknown', max_length=100)),
                ('other_auth_email', models.CharField(default='other@example.com', max_length=150)),
                ('other_auth_affiliation', models.CharField(default='No affiliation', max_length=100)),
                ('other_auth_mobile', models.CharField(default='N/A', max_length=20)),
                ('paper_keyword', models.CharField(default='No keywords', max_length=100)),
                ('reviewer_comments', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmissions', to='Author.conference')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resubmissions', to='Author.paper')),
                ('user', models.ForeignKey(limit_choices_to={'is_auth': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='assigned_reviewers',
            field=models.ManyToManyField(limit_choices_to={'is_reviewer': True}, related_name='assigned_papers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='Author.conference'),
        ),
        migrations.AddField(
            model_name='paper',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_auth': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='user',
            field=models.ForeignKey(limit_choices_to={'is_conference_admin': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
