# Generated by Django 4.1.7 on 2023-11-19 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resubmite_paper',
            name='assigned_reviewers',
            field=models.ManyToManyField(limit_choices_to={'is_reviewer': True}, related_name='re_assigned_papers', to=settings.AUTH_USER_MODEL),
        ),
    ]
