# Generated by Django 4.1.7 on 2023-11-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0002_resubmite_paper_assigned_reviewers'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='reviewer_id',
            field=models.IntegerField(default=1),
        ),
    ]
