# Generated by Django 4.1.7 on 2023-11-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0003_reviewerprofile_reviewer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='is_mail_verify',
            field=models.BooleanField(default=False),
        ),
    ]
