# Generated by Django 4.1.7 on 2023-11-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Author', '0005_paper_reviewer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='reviewer_status',
        ),
    ]
